stages:
  - build
  - test

build website:
  stage: build
  image: node:16
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public

test artifact:
  stage: test
  script:
    - grep "Gatsby" ./public/index.html
    - grep "xxxxxxxx" ./public/index.html